apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: dashkube
  name: dashkube
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dashkube
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: dashkube
    spec:
      hostNetwork: true
      containers:
      - env:
        - name: MAC_URL_CSV
          value: /configmap/example_mac_url.csv
        image: imartyn/dashkube
        name: dashkube
        resources: {}
        volumeMounts:
        - name: configmap
          mountPath: /configmap
      volumes:
        - name: configmap
          configMap:
            name: dashkube-urls
status: {}
